name: 'XML Validation'
description: 'RNG (with embedded schematron) validation.'
inputs:
  rng:
    description: 'Path to RNG schema'
    required: true
  dir:
    description: 'Directory of XML files to validate'
runs:
  using: "composite"
  steps:
      run: ant -f build.xml
      shell: bash