name: 'XML Validation'
description: 'RNG (with embedded schematron) validation.'
inputs:
  rng:
    description: 'Path to RNG schema'
  dir:
    description: 'Directory of XML files to validate'  
runs:
  using: 'composite'
  steps:
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run build
      run: ant -f build.xml           