name: 'XML Validation'
description: 'RNG (with embedded schematron) validation.'
inputs:
  rng:
    description: 'Path to RNG schema'
    required: true
  dir:
    description: 'Directory of XML files to validate'
    required: true
  failOnError:
    description: "Whether or not the build should fail on error"
    required: false
    default: true
runs:
  using: "composite"
  steps:
    - run: ant -f ${{ github.action_path }}/build.xml -Drng=${{ inputs.rng }} -Ddir=${{ inputs.dir }} -DfailOnError=${{ inputs.failOnError }}
      shell: bash