name: Test the Validator
on: push
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Test the action
        uses: ./
        with:
            rng: ${{ github.workspace }}/test/schema/tei_all.rng
            dir: ${{ github.workspace }}/test/xml
        